@baseUrl = http://localhost:8080
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoic2FuZGJveDEyMyJ9.T5Syh6MHFyq3FLvFgc7aUax7hlfaRjlrko33PQINmAg

### Get Health
GET {{baseUrl}}/api/v1/health
Authorization: Bearer {{accessToken}}

### Get List of sandboxes
GET {{baseUrl}}/api/v1/sandboxes
Authorization: Bearer {{accessToken}}

### Create a new sandbox

# @name createSandbox
POST {{baseUrl}}/api/v1/sandboxes
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Sandbox1"
}

### Get last created Sandbox by id
@lastSandbox = {{createSandbox.response.headers.Location}}
GET {{baseUrl}}{{createSandbox.response.headers.Location}}
Authorization: Bearer {{accessToken}}

### Update last created Sandbox by id with new expiration date
@lastSandbox = {{createSandbox.response.headers.Location}}
PATCH {{baseUrl}}{{createSandbox.response.headers.Location}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "expires_at": "2024-01-01T21:54:42.123Z"
}

### Delete last created Sandbox by id
@lastSandbox = {{createSandbox.response.headers.Location}}
DELETE {{baseUrl}}{{createSandbox.response.headers.Location}}
Authorization: Bearer {{accessToken}}
