@baseUrl = http://localhost:8080
@readToken = eyJhbGciOiJFUzI1NiIsImtpZCI6ImZha2Uta2V5LWlkIiwidHlwIjoiSldUIn0.eyJhdWQiOlsiZXhhbXBsZS11c2VycyJdLCJpc3MiOiJmYWtlLWlzc3VlciIsInBlcm0iOltdfQ.0MlqZSwJ_kp98E6NReGmGRoGp2p2KGsO5HPGqq3E37Z6SLF3JNCHwifEEF9bRz6WEPWkpRWM5Dmaf9hwAEjyfQ
@writeToken = eyJhbGciOiJFUzI1NiIsImtpZCI6ImZha2Uta2V5LWlkIiwidHlwIjoiSldUIn0.eyJhdWQiOlsiZXhhbXBsZS11c2VycyJdLCJpc3MiOiJmYWtlLWlzc3VlciIsInBlcm0iOlsic2FuZGJveDp3Il19.BG7rHBZHeb0mOFzTgG7ZEgMSTSSRuw1X4jBoZ5xfbaJ-A8W_8XoftyC8BY7_G_8B7Uk_NbZkfH07p1H5CI-5cg

### Get Health
GET {{baseUrl}}/health
Authorization: BearerAuth {{readToken}}

### Get List of sandboxes
GET {{baseUrl}}/sandboxes?limit=100&offset=0
Authorization: BearerAuth {{readToken}}

### Create a new sandbox

# @name createSandbox
POST {{baseUrl}}/sandboxes
Content-Type: application/json
Accept: application/json
Authorization: BearerAuth {{writeToken}}

{
    "name": "SandboxNew11",
    "expiresAt": "2025-01-01T00:00:00.000Z"
}

### Update last created Sandbox with new expiration date
PATCH {{baseUrl}}/sandboxes/f9de3cdf-f7ed-4c1d-8a38-e40666346f07
Content-Type: application/json
Accept: application/json
Authorization: BearerAuth {{writeToken}}

{
    "expiresAt": "2024-01-01T21:54:42.123Z"
}

### Delete last created Sandbox
DELETE {{baseUrl}}/sandboxes/546f1c5b-e68a-4385-8524-da63785e538d
Authorization: BearerAuth {{writeToken}}


### Get Sandbox by Name
GET {{baseUrl}}/sandboxes/name/SandboxNew10
Authorization: BearerAuth {{readToken}}

### Get Sandbox by id

GET {{baseUrl}}/sandboxes/546f1c5b-e68a-4385-8524-da63785e538d
Authorization: BearerAuth {{readToken}}


