@baseUrl = http://localhost:8080
@accessToken = 

### Get Health
GET {{baseUrl}}/api/v1/health
Authorization: Bearer {{accessToken}}

### Get List of sandboxes
GET {{baseUrl}}/api/v1/sandboxes?limit=5&offset=10
Authorization: Bearer {{accessToken}}

### Create a new sandbox

# @name createSandbox
POST {{baseUrl}}/api/v1/sandboxes
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Sandbox3",
    "expires_at": "2025-01-01T00:00:00.000Z"
}

### Get last created Sandbox by id
@lastSandbox = {{createSandbox.response.headers.Location}}
GET {{baseUrl}}{{createSandbox.response.headers.Location}}
Authorization: Bearer {{accessToken}}

### Update last created Sandbox with new expiration date
@lastSandbox = {{createSandbox.response.headers.Location}}
PATCH {{baseUrl}}{{createSandbox.response.headers.Location}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "expires_at": "2024-01-01T21:54:42.123Z"
}

### Delete last created Sandbox
@lastSandbox = {{createSandbox.response.headers.Location}}
DELETE {{baseUrl}}{{createSandbox.response.headers.Location}}
Authorization: Bearer {{accessToken}}

#########################################################################################


### Get Sandbox by Name
@lastSandbox = {{createSandbox.response.headers.Location}}
GET {{baseUrl}}/api/v1/sandboxes/name/Sandbox3
Authorization: Bearer {{accessToken}}

### Get Sandbox by id

GET {{baseUrl}}/api/v1/sandboxes/72314611-6249-4ed5-84ce-8bbf406e1821
Authorization: Bearer {{accessToken}}


### Update Sandbox with new expiration date

PATCH {{baseUrl}}/api/v1/sandboxes/991b45e5-63cb-45c0-a33a-df6d7a6e21d5
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "expires_at": "2025-01-01T21:54:42.123Z"
}

### Delete Sandbox

DELETE {{baseUrl}}/api/v1/sandboxes/73cbaf92-57b3-49e5-923a-5d42e7170b36
Authorization: Bearer {{accessToken}}



